---
- name: Add Red Hat access.redhat.com users
  hosts: localhost
  gather_facts: no
  vars_files:
    - .ansible/vault_file.yaml
  vars:
    - new_username: Test-Ted
  tasks:
    - name: Get Temp Token
      shell: "curl -s https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token -d grant_type=refresh_token -d client_id=rhsm-api -d refresh_token={{ RHSM_API_TOKEN }} | jq --raw-output .access_token"
      no_log: true
      register: token

    - name: Check connection
      uri:
        url: https://api.access.redhat.com/account/v1/accounts
        method: GET
        headers:
          Accept: "application/json"
          Authorization: "Bearer {{ token.stdout }}"

    - name: Add username to RHSM portal
      uri:
        url: https://api.access.redhat.com/account/v1/accounts/540155/users
        user: "{{ RHSM_USERNAME }}"
        password: "{{ RHSM_API_TOKEN }}"
        method: POST
        headers: 
          Accept: "application/json"
        body_format: json
        body: '{"body": {"address": {"city": "Raleigh","country": "US","county": "Wake","state": "NC","streets": ["100 E Davie St"],"zipCode": "27601"},"email": "testted@redhat.com","firstName": "Test","lastName": "Ted","permissions": ["portal_manage_subscriptions","portal_manage_cases","portal_system_management","portal_download"],"phone": "19195555555","roles": ["organization_administrator"],"salutation": "Mr.","status": "enabled","username": "TestTed@redhat.com"}}'
        

    #- name: Check that username is present

